// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8QJHX8dtfceGIe7-D7Y59wlAmQAd-FK4',
    appId: '1:275956033859:web:731573759c7f8b8f8a7f6',
    messagingSenderId: '275956033859',
    projectId: 'money-tracker-7a520',
    authDomain: 'money-tracker-7a520.firebaseapp.com',
    storageBucket: 'money-tracker-7a520.firebasestorage.app',
    measurementId: 'G-XP6K5WH39Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8QJHX8dtfceGIe7-D7Y59wlAmQAd-FK4',
    appId: '1:275956033859:web:731573759c7f8b8f8a7f6',
    messagingSenderId: '275956033859',
    projectId: 'money-tracker-7a520',
    storageBucket: 'money-tracker-7a520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc8QJHX8dtfceGIe7-D7Y59wlAmQAd-FK4',
    appId: '1:275956033859:web:731573759c7f8b8f8a7f6',
    messagingSenderId: '275956033859',
    projectId: 'money-tracker-7a520',
    storageBucket: 'money-tracker-7a520.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc8QJHX8dtfceGIe7-D7Y59wlAmQAd-FK4',
    appId: '1:275956033859:web:731573759c7f8b8f8a7f6',
    messagingSenderId: '275956033859',
    projectId: 'money-tracker-7a520',
    storageBucket: 'money-tracker-7a520.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8QJHX8dtfceGIe7-D7Y59wlAmQAd-FK4',
    appId: '1:275956033859:web:731573759c7f8b8f8a7f6',
    messagingSenderId: '275956033859',
    projectId: 'money-tracker-7a520',
    storageBucket: 'money-tracker-7a520.firebasestorage.app',
  );
}